apiVersion: v1
kind: PersistentVolume
metadata:
  name: newsletter-pv
  labels:
    app: newsletter
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""   # <--- Add this
  hostPath:
    path: /mnt/data

